version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: blogidb
      POSTGRES_USER: blogiuser
      POSTGRES_PASSWORD: blogipassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://blogiuser:blogipassword@db:5432/blogidb

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
